"""LLMTrace 常量定义."""

from __future__ import annotations

TEST_SUITE_VERSION = "1.0"
MAX_RESPONSE_BYTES_DEFAULT = 64 * 1024  # 64 KB
MAX_OUTPUT_TOKENS_DEFAULT = 64
DEFAULT_REPEAT_COUNT = 3
DEFAULT_TIMEOUT = 30.0
DEFAULT_RETRY_COUNT = 2
SCHEMA_VERSION = "1.0"
