"""LLMTrace 常量定义."""

from __future__ import annotations

TEST_SUITE_VERSION = "1.0"
MAX_RESPONSE_BYTES_DEFAULT = 64 * 1024  # 64 KB
MAX_OUTPUT_TOKENS_DEFAULT = 64
DEFAULT_REPEAT_COUNT = 3
DEFAULT_TIMEOUT = 30.0
DEFAULT_RETRY_COUNT = 2
SCHEMA_VERSION = "1.0"

# CLI 默认值：第三方中转绝大多数为 OpenAI-compatible（§6）；
# LLMTRACE_API_KEY 是默认 API Key 环境变量（§7）。
DEFAULT_PROTOCOL = "openai"
DEFAULT_API_KEY_ENV = "LLMTRACE_API_KEY"
